browser=chrome
baseUrl=http://localhost:7080/
implicitWait=10
pageLoadTimeout=30

# Görsel izleme modu (Açmak için true, kapatmak için false yap)
visualMode=True
# İşlem başı bekleme süresi
visualSleepMs=500

